<?php
//Define RABBITMQ Data
DEFINE('RABBITMQ_HOST', '127.0.0.1');
DEFINE('RABBITMQ_PORT', '5672');
DEFINE('RABBITMQ_USER', 'guest');
DEFINE('RABBITMQ_PASS', 'guest');

//Define ELASTICSEARCH Data
DEFINE('ELASTICSEARCH_HOST', '127.0.0.1');
DEFINE('ELASTICSEARCH_PORT', '9200');
DEFINE('ELASTICSEARCH_SCHEME', 'http');

//PATH
define('PROD_PATH','/home/ttrivelato/p/BackEndBr-07_03_2017/');
